### ISSUE TITLE
Unsupported operation: Cannot set value in unmodifiable Map [Flutter for Windows]

### ISSUE THREAD

**Issue by atul-chaudhary** [ueman/feedback#124] opened 2021-10-01 05:22 UTC
Version - 2.0.0

Logs

```
Unsupported operation: Cannot set value in unmodifiable Map

The relevant error-causing widget was: 
  FeedbackLocalization FeedbackLocalization:file:///C:/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/feedback-2.0.0/lib/src/utilities/feedback_app.dart:24:12
When the exception was thrown, this was the stack: 
#0      _ImmutableMap.[]= (dart:core-patch/immutable_map.dart:74:5)
#1      initializeDateFormattingCustom (package:intl/date_symbol_data_custom.dart:35:19)
#2      loadDateIntlDataIfNotLoaded.<anonymous closure> (package:flutter_localizations/src/utils/date_localizations.dart:25:9)
#3      CastMap.forEach.<anonymous closure> (dart:_internal/cast.dart:288:8)
#4      _ImmutableMap.forEach (dart:core-patch/immutable_map.dart:43:8)
#5      CastMap.forEach (dart:_internal/cast.dart:287:13)
#6      loadDateIntlDataIfNotLoaded (package:flutter_localizations/src/utils/date_localizations.dart:21:8)
#7      _GlobalCupertinoLocalizationsDelegate.load.<anonymous closure> (package:flutter_localizations/src/cupertino_localizations.dart:468:7)
#8      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:314:23)
#9      _GlobalCupertinoLocalizationsDelegate.load (package:flutter_localizations/src/cupertino_localizations.dart:467:32)
#10     _loadAll (package:flutter/src/widgets/localizations.dart:55:49)
#11     _LocalizationsState.load (package:flutter/src/widgets/localizations.dart:532:62)
#12     _LocalizationsState.initState (package:flutter/src/widgets/localizations.dart:497:5)
#13     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4805:57)
#14     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4638:5)
...     Normal element mounting (29 frames)
#43     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673:14)
#44     Element.updateChild (package:flutter/src/widgets/framework.dart:3425:18)
#45     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1198:16)
#46     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1167:5)
#47     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1112:18)
#48     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2573:19)
#49     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1111:13)
#50     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:944:7)
#51     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:924:7)
(elided 11 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
====================================================================================================
flutter: calledReturn In int_logic 0
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: NoSuchMethodError: The method 'findAncestorStateOfType' was called on null.
Receiver: null
Tried calling: findAncestorStateOfType<NavigatorState>()
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:63:5)
#1      Navigator.of (package:flutter/src/widgets/navigator.dart:2736:40)
#2      _MyAppState.initDBForInternal.<anonymous closure> (package:ide/main.dart:139:19)
#3      _rootRunUnary (dart:async/zone.dart:1436:47)
#4      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
<asynchronous suspension>

```

Tried calling BetterFeedback inside both run App and for materialApp as well but the same error for both.
Also tried removing initializeDateFormatting() but nothing is working.

**Comment by atul-chaudhary** [comment] 2021-10-01 05:35
Removing the initializeDateFormatting() will solve the issue the but what if i wanted to use it, If there is a way please let me know.

**Comment by ueman** [comment] 2021-10-01 05:53
Can you share a code snippet which causes this?

**Comment by ueman** [comment] 2021-11-02 18:57
@atul-chaudhary Can you share code to reproduce this problem? Otherwise I will close this issue because I'm not able to debug this issue.

**Closed** 2021-11-15 18:59 UTC
Labels: bug
